Feature/security
wolox-training/jvg-java pull request #14
Opened 2020-09-21 21:26 UTC by julianvasquez-wolox

## Summary
- Security dependencies added to gradle
- Security Config and Custom Autenthication Provider for basic authentication added
- Integration tests 
- Unit tests for Authentication Provider

## Trello Card
- https://trello.com/c/3DJDwSpB/23-integrar-spring-security

2020-09-23 22:00 UTC, facucompe requested changes

2020-09-23 22:00 UTC, facucompe commented on src/main/java/wolox/training/TrainingApplication.java
> +	@Bean
Let's move this Bean to a @Configuration class

2020-09-23 22:00 UTC, facucompe commented on src/test/java/wolox/training/security/CustomAuthenticationProviderTest.java
> +    given(passwordEncoder.matches(authentication.getCredentials().toString(),user.getPassword())).willReturn(true);
verify this mock is being called

2020-09-23 22:00 UTC, facucompe commented on src/test/java/wolox/training/security/CustomAuthenticationProviderTest.java
> +    given(passwordEncoder.matches(authentication.getCredentials().toString(),user.getPassword())).willReturn(false);
Same here

2020-09-23 22:01 UTC, facucompe commented on src/main/java/wolox/training/TrainingApplication.java
> +	@Bean
hahah, i tag a github user

2020-09-24 18:29 UTC, facucompe approved these changes

2020-09-25 20:24 UTC, rabinovichm approved these changes

2020-09-25 22:24 UTC, merged